### ISSUE TITLE
Listings form.

### ISSUE THREAD

**Issue by mal1k** [mal1k/nhr-admin#2]
Что делать и как быть с переносом с текущей версии:
1. блок features? **(это JS блок)**
2. блок hours? **(это JS блок)**
3. блок Listing Badges? **Я не понимаю что это и как он должен работать.** 

Еще мне надо, чтобы ты написал cписок по валидации всех полей, какие проверки и куда пихать и список полей в разных подписках оставлять, как в текущей версии или будут новые?

**Comment by Morgan2017** [comment]
1. JS блоки это обсудите все с Оксаной
2. тоже самое
3. Badges пока накидай форму = чисто UI а остальное потом будем делать как уточню требования

валидация полей будет такая же как в текущем сайте

**Comment by mal1k** [comment]
Жду badges от Оксаны. 
Функционально чекбокс привязал.
Всё работает, остался только фронт.
